### ISSUE TITLE
Invalid schematron file

### ISSUE THREAD

**Issue by rosaldo260** [isdoc/isdoc.github.io#2]
Can't get schematron file [isdoc-6.0.2.sch](https://raw.githubusercontent.com/isdoc/isdoc.github.io/main/sch/isdoc-6.0.2.sch) validation working.
For example, if you try to use it with following tool: https://www.itb.ec.europa.eu/xml/upload it says: `An error occurred during the validation: Schematron file [isdoc-6.0.2.sch] is invalid.`

**Comment by kosek** [comment]
Duplicate of https://github.com/isdoc/isdoc.github.io/pull/1

Will be fixed once a new release is published
